/**
 * Emits the onboarding-form seed migration from the typed content in
 * supabase/seed/onboarding/. Run with plain Node (type stripping, Node ≥ 22.18):
 *
 *   node scripts/gen-onboarding-seed.mts
 *
 * Every row is inserted with `on conflict (id) do nothing`, so re-running the migration
 * against the already-provisioned cloud project is safe and CMS edits are never overwritten.
 */
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  briefSections,
  examples,
  fields,
  flagRules,
  followups,
  prompts,
  screens,
  texts,
} from '../supabase/seed/onboarding/index.ts';

const OUT = join(dirname(fileURLToPath(import.meta.url)), '..', 'supabase', 'migrations', '20260921000011_onboarding_seed.sql');

type Cell = string | number | boolean | null | undefined | object;

function lit(value: Cell, kind: 'scalar' | 'jsonb' | 'text[]' = 'scalar'): string {
  if (value === null || value === undefined) return 'null';
  if (kind === 'jsonb') return `'${JSON.stringify(value).replace(/'/g, "''")}'::jsonb`;
  if (kind === 'text[]') {
    const arr = value as string[];
    if (!arr.length) return `'{}'::text[]`;
    return `array[${arr.map((v) => lit(v)).join(', ')}]::text[]`;
  }
  if (typeof value === 'boolean') return value ? 'true' : 'false';
  if (typeof value === 'number') return String(value);
  return `'${String(value).replace(/'/g, "''")}'`;
}

type ColumnSpec = readonly [column: string, kind?: 'jsonb' | 'text[]'];

function insert(table: string, columns: readonly ColumnSpec[], rows: readonly object[]): string {
  const cols = columns.map(([c]) => c).join(', ');
  const values = rows
    .map((row) => {
      const cells = row as Record<string, Cell>;
      return `  (${columns.map(([c, kind]) => lit(cells[c], kind ?? 'scalar')).join(', ')})`;
    })
    .join(',\n');
  return `insert into ${table} (${cols}) values\n${values}\non conflict (id) do nothing;\n`;
}

const sql = [
  `-- GENERATED by scripts/gen-onboarding-seed.ts from supabase/seed/onboarding/ — do not edit by hand.`,
  `-- Initial content of the onboarding form: screens, fields, follow-ups, flag rules, brief`,
  `-- sections, texts, prompts and worked examples. Supabase is the runtime source of truth;`,
  `-- rows already present (edited in /admin) are left untouched.`,
  ``,
  insert(
    'onb_screens',
    [['id'], ['sort'], ['kind'], ['title_de'], ['title_en'], ['short_de'], ['short_en'], ['intro_de'], ['intro_en'], ['active']],
    screens,
  ),
  insert(
    'onb_fields',
    [
      ['id'], ['screen_id'], ['sort'], ['type'], ['label_de'], ['label_en'], ['help_de'], ['help_en'],
      ['placeholder_de'], ['placeholder_en'], ['required'], ['allow_dont_know'], ['ai_check'],
      ['options', 'jsonb'], ['config', 'jsonb'], ['show_when', 'jsonb'], ['active'],
    ],
    fields,
  ),
  insert(
    'onb_followups',
    [
      ['id'], ['sort'], ['trigger', 'jsonb'], ['question_de'], ['question_en'], ['quick_replies', 'jsonb'],
      ['writes_to'], ['mode'], ['raises', 'jsonb'], ['active'],
    ],
    followups,
  ),
  insert(
    'onb_flag_rules',
    [['id'], ['code'], ['detail'], ['severity'], ['conditions', 'jsonb'], ['note_de'], ['note_en'], ['sort'], ['active']],
    flagRules,
  ),
  insert(
    'onb_brief_sections',
    [['id'], ['sort'], ['title_de'], ['title_en'], ['instructions'], ['source_fields', 'text[]'], ['generated_by'], ['active']],
    briefSections,
  ),
  insert('onb_texts', [['id'], ['key'], ['locale'], ['title'], ['content_markdown']], texts),
  insert('onb_prompts', [['id'], ['content'], ['note']], prompts),
  insert(
    'onb_examples',
    [['id'], ['title'], ['answers', 'jsonb'], ['brief', 'jsonb'], ['sort'], ['active']],
    examples,
  ),
].join('\n');

writeFileSync(OUT, sql, 'utf8');
console.log(
  `wrote ${OUT}: ${screens.length} screens, ${fields.length} fields, ${followups.length} follow-ups, ` +
    `${flagRules.length} flag rules, ${briefSections.length} sections, ${texts.length} texts, ` +
    `${prompts.length} prompts, ${examples.length} examples`,
);
