/**
 * Emits the onboarding-form seed migration from the typed content in
 * supabase/seed/onboarding/. Run with plain Node (type stripping, Node ≥ 22.18):
 *
 *   node scripts/gen-onboarding-seed.mts
 *
 * Every row is inserted with `on conflict (id) do nothing`, so re-running the migration
 * against the already-provisioned cloud project is safe and CMS edits are never overwritten.
 */
import { existsSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  briefSections,
  examples,
  fields,
  flagRules,
  followups,
  prompts,
  screens,
  texts,
} from '../supabase/seed/onboarding/index.ts';
import { retiredFieldIds } from '../supabase/seed/onboarding/fields.ts';

/**
 * Default: the original insert-only seed. With `--upsert <file>` the same content is
 * emitted as an UPSERT, which is how a rewritten form definition reaches rows that are
 * already live. That overwrites CMS edits on purpose — the new content is the source.
 */
const args = process.argv.slice(2);
const upsertIndex = args.indexOf('--upsert');
const UPSERT = upsertIndex !== -1;
const MIGRATIONS = join(dirname(fileURLToPath(import.meta.url)), '..', 'supabase', 'migrations');
const OUT = UPSERT ? join(MIGRATIONS, args[upsertIndex + 1]!) : join(MIGRATIONS, '20260921000011_onboarding_seed.sql');

type Cell = string | number | boolean | null | undefined | object;

function lit(value: Cell, kind: 'scalar' | 'jsonb' | 'text[]' = 'scalar'): string {
  if (value === null || value === undefined) return 'null';
  if (kind === 'jsonb') return `'${JSON.stringify(value).replace(/'/g, "''")}'::jsonb`;
  if (kind === 'text[]') {
    const arr = value as string[];
    if (!arr.length) return `'{}'::text[]`;
    return `array[${arr.map((v) => lit(v)).join(', ')}]::text[]`;
  }
  if (typeof value === 'boolean') return value ? 'true' : 'false';
  if (typeof value === 'number') return String(value);
  return `'${String(value).replace(/'/g, "''")}'`;
}

type ColumnSpec = readonly [column: string, kind?: 'jsonb' | 'text[]'];

function insert(table: string, columns: readonly ColumnSpec[], rows: readonly object[]): string {
  const cols = columns.map(([c]) => c).join(', ');
  const values = rows
    .map((row) => {
      const cells = row as Record<string, Cell>;
      return `  (${columns.map(([c, kind]) => lit(cells[c], kind ?? 'scalar')).join(', ')})`;
    })
    .join(',\n');
  const conflict = UPSERT
    ? `on conflict (id) do update set ${columns
        .map(([c]) => c)
        .filter((c) => c !== 'id')
        .map((c) => `${c} = excluded.${c}`)
        .join(', ')}`
    : 'on conflict (id) do nothing';
  return `insert into ${table} (${cols}) values\n${values}\n${conflict};\n`;
}

const sql = [
  `-- GENERATED by scripts/gen-onboarding-seed.ts from supabase/seed/onboarding/ — do not edit by hand.`,
  UPSERT
    ? `-- Content of the onboarding form as of the 23 Sep 2026 spec: screens, fields, follow-ups,
` +
      `-- flag rules, brief sections, texts, prompts and worked examples. This one UPSERTS: it is a
` +
      `-- rewrite of the form, so it replaces what is in the CMS rather than skipping existing rows.`
    : `-- Initial content of the onboarding form: screens, fields, follow-ups, flag rules, brief
` +
      `-- sections, texts, prompts and worked examples. Supabase is the runtime source of truth;
` +
      `-- rows already present (edited in /admin) are left untouched.`,
  ``,
  UPSERT
    ? [
        `-- "Help me say this better" is a fifth prompt; the id check has to allow it first.`,
        'alter table onb_prompts drop constraint if exists onb_prompts_id_check;',
        'alter table onb_prompts add constraint onb_prompts_id_check',
        "  check (id in ('system', 'completeness', 'brief', 'rewrite', 'assist'));",
        '',
      ].join('\n')
    : '',
  insert(
    'onb_screens',
    [['id'], ['sort'], ['kind'], ['title_de'], ['title_en'], ['short_de'], ['short_en'], ['intro_de'], ['intro_en'], ['active']],
    screens,
  ),
  insert(
    'onb_fields',
    [
      ['id'], ['screen_id'], ['sort'], ['type'], ['label_de'], ['label_en'], ['help_de'], ['help_en'],
      ['placeholder_de'], ['placeholder_en'], ['required'], ['allow_dont_know'], ['ai_check'],
      ['options', 'jsonb'], ['config', 'jsonb'], ['show_when', 'jsonb'], ['active'],
    ],
    fields,
  ),
  insert(
    'onb_followups',
    [
      ['id'], ['sort'], ['trigger', 'jsonb'], ['question_de'], ['question_en'], ['quick_replies', 'jsonb'],
      ['writes_to'], ['mode'], ['raises', 'jsonb'], ['active'],
    ],
    followups,
  ),
  insert(
    'onb_flag_rules',
    [['id'], ['code'], ['detail'], ['severity'], ['conditions', 'jsonb'], ['note_de'], ['note_en'], ['sort'], ['active']],
    flagRules,
  ),
  insert(
    'onb_brief_sections',
    [['id'], ['sort'], ['title_de'], ['title_en'], ['instructions'], ['source_fields', 'text[]'], ['generated_by'], ['active']],
    briefSections,
  ),
  insert('onb_texts', [['id'], ['key'], ['locale'], ['title'], ['content_markdown']], texts),
  insert('onb_prompts', [['id'], ['content'], ['note']], prompts),
  insert(
    'onb_examples',
    [['id'], ['title'], ['answers', 'jsonb'], ['brief', 'jsonb'], ['sort'], ['active']],
    examples,
  ),
  UPSERT
    ? `-- Questions the new definition dropped: switched off, never deleted, so the answers\n` +
      `-- already given to them survive in the records that carry them.\n` +
      `update onb_fields set active = false where id in (${retiredFieldIds.map((id) => lit(id)).join(', ')});\n` +
      `\n-- The timeline the 23 Sep 2026 terms describe: 10 days to the design, 3 weeks to build.\n` +
      `update app_settings set value = '3'::jsonb where key in ('onb_build_weeks_min', 'onb_build_weeks_max');\n`
    : '',
].join('\n');

// An applied migration is history: only the new file may be written.
if (!UPSERT && existsSync(OUT)) {
  throw new Error(`${OUT} is already applied — pass --upsert <new file name> to emit the rewrite instead.`);
}
writeFileSync(OUT, sql, 'utf8');
console.log(
  `wrote ${OUT}: ${screens.length} screens, ${fields.length} fields, ${followups.length} follow-ups, ` +
    `${flagRules.length} flag rules, ${briefSections.length} sections, ${texts.length} texts, ` +
    `${prompts.length} prompts, ${examples.length} examples`,
);
